import React, { useState } from 'react';
import { GeneratedContent, GeneratedImage } from '../types';

interface ResultCardProps {
  content: GeneratedContent;
  image: GeneratedImage;
  onReset: () => void;
}

const ResultCard: React.FC<ResultCardProps> = ({ content, image, onReset }) => {
  const [copied, setCopied] = useState(false);

  const handleCopyCaption = () => {
    navigator.clipboard.writeText(`${content.title}\n\n${content.caption}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = image.url;
    link.download = `recovery-vision-${Date.now()}.jpg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="w-full bg-white rounded-2xl shadow-xl border border-slate-100 overflow-hidden animate-fade-in-up">
      <div className="relative group">
        <img 
          src={image.url} 
          alt={content.imagePrompt} 
          className="w-full h-auto object-cover max-h-[600px]"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end justify-end p-4">
          <button 
            onClick={handleDownload}
            className="bg-white text-slate-900 px-4 py-2 rounded-full shadow-lg font-medium text-sm hover:bg-brand-50 flex items-center gap-2 transition-transform hover:scale-105 active:scale-95"
          >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-4 h-4">
              <path fillRule="evenodd" d="M12 2.25a.75.75 0 01.75.75v11.69l3.22-3.22a.75.75 0 111.06 1.06l-4.5 4.5a.75.75 0 01-1.06 0l-4.5-4.5a.75.75 0 111.06-1.06l3.22 3.22V3a.75.75 0 01.75-.75zm-9 13.5a.75.75 0 01.75.75v2.25a1.5 1.5 0 001.5 1.5h13.5a1.5 1.5 0 001.5-1.5V16.5a.75.75 0 011.5 0v2.25a3 3 0 01-3 3H5.25a3 3 0 01-3-3V16.5a.75.75 0 01.75-.75z" clipRule="evenodd" />
            </svg>
            Download Image
          </button>
        </div>
      </div>

      <div className="p-6 md:p-8">
        <div className="flex items-start justify-between gap-4 mb-4">
          <h2 className="text-2xl font-bold text-slate-800 leading-tight">
            {content.title}
          </h2>
        </div>

        <div className="prose prose-slate max-w-none mb-6">
          <p className="text-slate-600 text-lg leading-relaxed">
            {content.caption}
          </p>
        </div>

        <div className="flex items-center justify-between pt-6 border-t border-slate-100">
            <div className="flex gap-3">
                <button
                    onClick={handleCopyCaption}
                    className={`text-sm font-medium px-4 py-2 rounded-lg transition-all border ${copied ? 'bg-green-50 text-green-700 border-green-200' : 'bg-slate-50 text-slate-600 border-slate-200 hover:border-brand-300 hover:text-brand-700'}`}
                >
                    {copied ? 'Copied!' : 'Copy Text'}
                </button>
                
                <button 
                    onClick={onReset}
                    className="text-sm font-medium text-slate-500 px-4 py-2 rounded-lg hover:bg-slate-50 transition-colors"
                >
                    Create Another
                </button>
            </div>
            <div className="text-xs text-slate-400 italic hidden sm:block">
              Generated by Gemini & Imagen
            </div>
        </div>

        <details className="mt-6 group">
          <summary className="list-none flex items-center gap-2 text-xs font-medium text-slate-400 cursor-pointer hover:text-brand-600 transition-colors select-none">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-3 h-3 transition-transform group-open:rotate-90">
              <path fillRule="evenodd" d="M4.5 5.653c0-1.426 1.529-2.33 2.779-1.643l11.54 6.348c1.295.712 1.295 2.573 0 3.285L7.28 19.991c-1.25.687-2.779-.217-2.779-1.643V5.653z" clipRule="evenodd" />
            </svg>
            View Prompt Details
          </summary>
          <div className="mt-2 p-3 bg-slate-50 rounded-lg border border-slate-100">
            <p className="text-xs text-slate-500 font-mono leading-relaxed">
              {content.imagePrompt}
            </p>
          </div>
        </details>
      </div>
    </div>
  );
};

export default ResultCard;